name: deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t kiosk-app . 
          docker tag kiosk-app ${{ secrets.DOCKER_HUB_USERNAME }}/kiosk-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kiosk-app:${{ github.sha }}

      - name: SSH Connection and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker rm -f kiosk-app
            sudo docker system prune -af
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/kiosk-app:${{ github.sha }}
            sudo docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/kiosk-app:${{ github.sha }} kiosk-app
            sudo docker run \
            -e DB_HOST="${{ env.DB_HOST }}" \
            -e DB_USER="${{ env.DB_USER }}" \
            -e DB_PASSWORD="${{ env.DB_PASSWORD }}" \
            -d --name kiosk-app -e TZ=Asia/Seoul -p 8080:8080 kiosk-app